### PR TITLE
Add "directions to here" on the expanded menu

### LINKED ISSUE #62: Add "directions to here" on the expanded menu
**Have an idea for an additional feature?**
(a) Describe the feature
Adding "directions to here" on the expanded view for a location. "Directions to here" should sit at the very bottom of the business view card, and when clicked, should open marker at that location in Google Maps. See attached figma file (contact @jayktee for access).

https://www.figma.com/file/qPEgqcwOkKn2E6bQif4AKO/covid-website?node-id=263%3A139
image
image

### PR DESCRIPTION
**Pull request by chalkedgoose**
# Screen Recording
ezgif com-gif-maker

Closes #62

### CODE REVIEW

**Comment by charliehoffs** [comment]
Wait a minute.... this is possible?!?! This is _so_ cool; I love this feature!! Thank you so much for adding this in @calba5141114 ! The screenrecording looks fantastic. If you want to push it to the staging link I can take it for a spin!

**Comment by charliehoffs** [comment]
This looks amazing on the staging link, @calba5141114 . I'm so excited about this feature; many of our users asked for it in our testing interviews! I realize that two issues we might need to reconcile before pushing it to the site are 1) entries without locations (e.g. a mental health hotline) where the Google Maps page that comes up searches up "national domestic violence hotline    null" for example. Would it be possible to only have "Directions to here" display when there is an address associated with that entry? And 2) I'll just have to add in translations for the "Directions to here" text for Chinese, Vietnamese, Tagalog, and Malay. Then, this will be great to go!! 

Thanks for mobilizing on this feature addition. It's such a crucial add!

**Comment by chalkedgoose** [comment]
@charliehoffs The code has a condition so that the link only renders if nonnull directions exist.
I'm reasonably confident in Vue, but I think it would be good to have a team of folks manually test it.

**Comment by charliehoffs** [comment]
@calba5141114 When I search for entries without directions I think it might still populate a "Directions to here". Maybe the directions aren't "null" but filled with a zero or something else? I also noted that you had already added in the Spanish translation!:D If its easy to manually add in the other translations, they are:
Chinese: 前往这里的路线
Vietnamese: Chỉ đường đến đây
Tagalog: Mga direksyon papunta dito
Malay: Petunjuk ke sini
Or more formally they are row 337 in our translations spreadsheet.(https://docs.google.com/spreadsheets/d/17vQZZnKqq4IKXUDjHOsCCLYo0KTxUDsREE7b2Ev4Ang/edit?usp=sharing). I did not add their ID label because I wasn't sure what it should be. We can hard code it for now without using the formal translations sheet though, if we want/if possible! 
Screen Shot 2021-04-09 at 5 43 41 PM

Screen Shot 2021-04-09 at 5 44 13 PM

**Pull request merged**
